### ISSUE TITLE
hi could you please offer the firekeeper database? very thks!!!

### ISSUE THREAD

**Issue by Quyans** [ashawkey/NotVeryFastNeRF#1]
awesome work! could you please offer the firekeeper database? very thks!!!
my email is 648224071@qq.com. thank you very much!

**Comment by ashawkey** [comment]
@Quyans Yes, it is release in https://drive.google.com/drive/folders/1n_NOUzOsI8qwbBWYBi86q7he1PLxpthp?usp=sharing

**Comment by Quyans** [comment]
已收到邮件

**Comment by Quyans** [comment]
thank you very much! 👍 do you have the checkpoint file? so as to save the tedious time to train the model :)

**Comment by ashawkey** [comment]
Since this project is finished long ago, I cannot find the checkpoint now...
BTW, If you are interested in real-time nerf, I recommend to check [instant-ngp](https://github.com/NVlabs/instant-ngp) and my [torch-ngp](https://github.com/ashawkey/torch-ngp) reimplementation. They are much faster to train and also support interactive rendering.

**Comment by ashawkey** [comment]
something like this:
![image](https://user-images.githubusercontent.com/25863658/169950333-6479b2d6-a7ac-4818-9f22-fa92c359f58b.png)
